### ISSUE TITLE
AIMG.dll not found

### ISSUE THREAD

**Issue by dbarnhart** [Artomatix/ArtomatixImageLoader#15]
The latest version of this loader fails to extract the AIMG.dll in my test code (trivial C# console project loading an EXR image, installed via NuGet):

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Artomatix.ImageLoader.ImgLoader' threw an exception.
  Source=ArtomatixImageLoader
  StackTrace:
   at Artomatix.ImageLoader.ImgLoader.getReadCallback(Stream s)
   at Artomatix.ImageLoader.AImg..ctor(Stream stream, Boolean doDisposeStream)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\darry\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 13

Inner Exception 1:
TypeInitializationException: The type initializer for 'Artomatix.ImageLoader.NativeFuncs' threw an exception.

Inner Exception 2:
ArgumentException: Unable to load unmanaged module "C:\Users\darry\source\repos\ConsoleApp1\ConsoleApp1\bin\Debug\AIMG.dll": The operation completed successfully

Inner Exception 3:
Win32Exception: The operation completed successfully
```

I extracted the embedded DLL manually, but it then complains about missing native methods:

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Artomatix.ImageLoader.ImgLoader' threw an exception.
  Source=ArtomatixImageLoader
  StackTrace:
   at Artomatix.ImageLoader.ImgLoader.getReadCallback(Stream s)
   at Artomatix.ImageLoader.AImg..ctor(Stream stream, Boolean doDisposeStream)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\darry\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 13

Inner Exception 1:
TypeInitializationException: The type initializer for 'Artomatix.ImageLoader.NativeFuncs' threw an exception.

Inner Exception 2:
MissingMethodException: The unmanaged method "_AImgGetErrorDetails" does not exist
```

I tried to build it from source, but hunter complained about MSVC 2017 being unrecognized.

Would love to use this library, it seems very nice.

**Comment by mloccy** [comment]
@dbarnhart Just updated from our upstream repositries, it should now build in VS2017 note however we do not bundle native DLLs in this library any more as it causes problems with anti-virus software.

**Comment by dbarnhart** [comment]
It builds now. Thanks!
